afr_set_board_metadata(ID "CU345")
afr_set_board_metadata(DISPLAY_NAME "MW320 AWS IoT Development Kit")
afr_set_board_metadata(DESCRIPTION "Globalscale development kit based on AW-CU345 and Amazon FreeRTOS")
afr_set_board_metadata(VENDOR_NAME "Globalscale")
afr_set_board_metadata(FAMILY_NAME "Wireless Microcontroller")
afr_set_board_metadata(IS_ACTIVE "TRUE")
afr_set_board_metadata(DATA_RAM_MEMORY "512KB")
afr_set_board_metadata(PROGRAM_MEMORY "2MB")
afr_set_board_metadata(CODE_SIGNER "null")
afr_set_board_metadata(SUPPORTED_IDE "CMakeBuildSystem")
afr_set_board_metadata(RECOMMENDED_IDE "CMakeBuildSystem")
afr_set_board_metadata(IDE_CMakeBuildSystem_NAME "CMakeBuildSystem")
afr_set_board_metadata(IDE_CMakeBuildSystem_COMPILER "GCC")
afr_set_board_metadata(KEY_IMPORT_PROVISIONING "TRUE")

afr_set_board_metadata(IDE_CMakeBuildSystem_PROJECT_LOCATION "null")
afr_set_board_metadata(AWS_DEMOS_CONFIG_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}/aws_demos/config_files")
